spring:
  application:
    name: player-rx-boot
    pref-file: prefs.yaml
    res-library-file: res-library-file.yaml
    legacy-pref-file: prefs.properties
    resource-prefix-path: ${user.home}/.at/player-rx-boot/resources

  main:
    banner-mode: "console"
    lazy-initialization: false

  datasource:
    url            : jdbc:h2:file:${user.home}/.at/player-rx-boot/db/player-rx-boot.db;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username       : sa
    password       :
    driverClassName: org.h2.Driver

  jpa:
    entity-scan:
      packages: 'me.antoniocaccamo.player.rx.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
  
  resources:
    static-locations : classpath:/static, file:///${user.home}/.at/player-rx-boot
  
  h2:
    console:
      enabled : true

server:
  port : 9090
