//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.01 at 02:53:28 AM CEST 
//


package me.antoniocaccamo.player.rx.model.legacy.news;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for infosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="infosType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://sequencemovieplayer.antanysavage.it/news/schema}kinds" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "infosType", propOrder = {
    "kinds"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
public class InfosType {

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    protected List<KindType> kinds;

    /**
     * Gets the value of the kinds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kinds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKinds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KindType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public List<KindType> getKinds() {
        if (kinds == null) {
            kinds = new ArrayList<KindType>();
        }
        return this.kinds;
    }

}
