//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.01 at 02:53:28 AM CEST 
//


package me.antoniocaccamo.player.rx.model.legacy.news;

import javax.annotation.Generated;
import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for kindType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="kindType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://sequencemovieplayer.antanysavage.it/news/schema}tips"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="font" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="foregroundColor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="backgroundColor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kindType", propOrder = {
    "tips"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
public class KindType {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    protected TipType tips;
    @XmlAttribute(name = "id")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    protected BigInteger id;
    @XmlAttribute(name = "name")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    protected String name;
    @XmlAttribute(name = "font")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    protected String font;
    @XmlAttribute(name = "foregroundColor")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    protected String foregroundColor;
    @XmlAttribute(name = "backgroundColor")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    protected String backgroundColor;
    @XmlAttribute(name = "enabled")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    protected Boolean enabled;

    /**
     * Gets the value of the tips property.
     * 
     * @return
     *     possible object is
     *     {@link TipType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public TipType getTips() {
        return tips;
    }

    /**
     * Sets the value of the tips property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public void setTips(TipType value) {
        this.tips = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public String getFont() {
        return font;
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public void setFont(String value) {
        this.font = value;
    }

    /**
     * Gets the value of the foregroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public String getForegroundColor() {
        return foregroundColor;
    }

    /**
     * Sets the value of the foregroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public void setForegroundColor(String value) {
        this.foregroundColor = value;
    }

    /**
     * Gets the value of the backgroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public String getBackgroundColor() {
        return backgroundColor;
    }

    /**
     * Sets the value of the backgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public void setBackgroundColor(String value) {
        this.backgroundColor = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public Boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2019-05-01T02:53:28+02:00", comments = "JAXB RI v2.3.0")
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

}
