//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.01 at 02:53:28 AM CEST 
//


package me.antoniocaccamo.player.rx.model.legacy.news;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.antanysavage.sm.player.jaxb.news package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and mail
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Infos_QNAME = new QName("http://sequencemovieplayer.antanysavage.it/news/schema", "infos");
    private final static QName _Kinds_QNAME = new QName("http://sequencemovieplayer.antanysavage.it/news/schema", "kinds");
    private final static QName _Tips_QNAME = new QName("http://sequencemovieplayer.antanysavage.it/news/schema", "tips");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.antanysavage.sm.player.jaxb.news
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InfosType }
     * 
     */
    public InfosType createInfosType() {
        return new InfosType();
    }

    /**
     * Create an instance of {@link KindType }
     * 
     */
    public KindType createKindType() {
        return new KindType();
    }

    /**
     * Create an instance of {@link TipType }
     * 
     */
    public TipType createTipType() {
        return new TipType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfosType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InfosType }{@code >}
     */
    @XmlElementDecl(namespace = "http://sequencemovieplayer.antanysavage.it/news/schema", name = "infos")
    public JAXBElement<InfosType> createInfos(InfosType value) {
        return new JAXBElement<InfosType>(_Infos_QNAME, InfosType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KindType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link KindType }{@code >}
     */
    @XmlElementDecl(namespace = "http://sequencemovieplayer.antanysavage.it/news/schema", name = "kinds")
    public JAXBElement<KindType> createKinds(KindType value) {
        return new JAXBElement<KindType>(_Kinds_QNAME, KindType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TipType }{@code >}
     */
    @XmlElementDecl(namespace = "http://sequencemovieplayer.antanysavage.it/news/schema", name = "tips")
    public JAXBElement<TipType> createTips(TipType value) {
        return new JAXBElement<TipType>(_Tips_QNAME, TipType.class, null, value);
    }

}
