//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.01 at 02:53:28 AM CEST 
//


package me.antoniocaccamo.player.rx.model.legacy.sequences;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.antanysavage.sm.player.jaxb.sequences package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and mail
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Sequence_QNAME = new QName("http://sequencemovieplayer.antanysavage.it/sequences/schema", "sequence");
    private final static QName _Videos_QNAME = new QName("http://sequencemovieplayer.antanysavage.it/sequences/schema", "videos");
    private final static QName _Video_QNAME = new QName("http://sequencemovieplayer.antanysavage.it/sequences/schema", "video");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.antanysavage.sm.player.jaxb.sequences
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SequenceType }
     * 
     */
    public SequenceType createSequenceType() {
        return new SequenceType();
    }

    /**
     * Create an instance of {@link VideosType }
     * 
     */
    public VideosType createVideosType() {
        return new VideosType();
    }

    /**
     * Create an instance of {@link VideoType }
     * 
     */
    public VideoType createVideoType() {
        return new VideoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SequenceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SequenceType }{@code >}
     */
    @XmlElementDecl(namespace = "http://sequencemovieplayer.antanysavage.it/sequences/schema", name = "sequence")
    public JAXBElement<SequenceType> createSequence(SequenceType value) {
        return new JAXBElement<SequenceType>(_Sequence_QNAME, SequenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VideosType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link VideosType }{@code >}
     */
    @XmlElementDecl(namespace = "http://sequencemovieplayer.antanysavage.it/sequences/schema", name = "videos")
    public JAXBElement<VideosType> createVideos(VideosType value) {
        return new JAXBElement<VideosType>(_Videos_QNAME, VideosType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VideoType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link VideoType }{@code >}
     */
    @XmlElementDecl(namespace = "http://sequencemovieplayer.antanysavage.it/sequences/schema", name = "video")
    public JAXBElement<VideoType> createVideo(VideoType value) {
        return new JAXBElement<VideoType>(_Video_QNAME, VideoType.class, null, value);
    }

}
