name: player-rx-boot build

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name : checkout
      uses : actions/checkout@master
      
    - name : gradle build
      uses : OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
      with :
        args: build -x test
  
    - name : list of distribution build/distributions
      run  : ls -lR build/distributions
      
    - name : download of distribution build/distributions
      uses : actions/download-artifact@v2
      with :
        path : build/distributions
     

 #  - name : gradle sonarqube
 #    uses : OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
 #    with :
 #      args: sonarqube -x test
